### ISSUE TITLE
Update Dart SDK constraints to support Dart 2.0

### ISSUE THREAD

**Issue by bkonyi** [matthewfranglen/dart-ini#4]

**Comment by matthewfranglen** [comment]
Thanks for opening this ticket. I think that [this](https://www.dartlang.org/dart-2) covers the constraint change that you desire. I will be able to make this change soon.

**Comment by bkonyi** [comment]
> Thanks for opening this ticket. I think that [this](https://www.dartlang.org/dart-2) covers the constraint change that you desire. I will be able to make this change soon.

Yes, that's basically right. You'll want to add this to your pubspec.yaml:

```yaml
environment:
  sdk: ">=2.0.0 <3.0.0"
```

**Comment by matthewfranglen** [comment]
Hi. I have uploaded a new version which I believe fixes this issue.

If you have any problems please reopen this issue or create a new one.

Thanks again.

**Comment by bkonyi** [comment]
Works for me! Thanks!
